/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AwardPointsModal: typeof import('./src/components/modals/awardPointsModal.vue')['default']
    CategoryRenderer: typeof import('./src/components/tutorials/CategoryRenderer.vue')['default']
    Classes: typeof import('./src/components/Classes.vue')['default']
    ClassForm: typeof import('./src/components/modals/ClassForm.vue')['default']
    ClassGroupView: typeof import('./src/components/ClassGroupView.vue')['default']
    ClassList: typeof import('./src/components/classList.vue')['default']
    ClassPerformance: typeof import('./src/components/ClassPerformance.vue')['default']
    Controls: typeof import('./src/components/controls.vue')['default']
    CreateItemModal: typeof import('./src/components/modals/CreateItemModal.vue')['default']
    FieldChecklist: typeof import('./src/components/tutorials/FieldChecklist.vue')['default']
    FieldDemoVideo: typeof import('./src/components/tutorials/FieldDemoVideo.vue')['default']
    FieldInfo: typeof import('./src/components/tutorials/FieldInfo.vue')['default']
    FieldRenderer: typeof import('./src/components/tutorials/FieldRenderer.vue')['default']
    FieldText: typeof import('./src/components/tutorials/FieldText.vue')['default']
    FieldWarning: typeof import('./src/components/tutorials/FieldWarning.vue')['default']
    GrouperModal: typeof import('./src/components/modals/GrouperModal.vue')['default']
    HelpButton: typeof import('./src/components/navigation/helpButton.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shop: typeof import('./src/components/Shop.vue')['default']
    StepsAndVideo: typeof import('./src/components/tutorials/StepsAndVideo.vue')['default']
    StudentConstraintsModal: typeof import('./src/components/modals/StudentConstraintsModal.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
    TopNav: typeof import('./src/components/navigation/topNav.vue')['default']
  }
}
