/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminNav: typeof import('./src/components/admin/AdminNav.vue')['default']
    AppContextMenu: typeof import('./src/components/common/AppContextMenu.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AwardPointsModal: typeof import('./src/components/modals/awardPointsModal.vue')['default']
    CategoryRenderer: typeof import('./src/components/tutorials/CategoryRenderer.vue')['default']
    Classes: typeof import('./src/components/Classes.vue')['default']
    ClassesFloatingBar: typeof import('./src/components/classes/ClassesFloatingBar.vue')['default']
    ClassFloatingBar: typeof import('./src/components/class/ClassFloatingBar.vue')['default']
    ClassForm: typeof import('./src/components/modals/ClassForm.vue')['default']
    ClassGroupView: typeof import('./src/components/ClassGroupView.vue')['default']
    ClassList: typeof import('./src/components/classList.vue')['default']
    CreateItemModal: typeof import('./src/components/modals/CreateItemModal.vue')['default']
    FieldChecklist: typeof import('./src/components/tutorials/FieldChecklist.vue')['default']
    FieldDemoVideo: typeof import('./src/components/tutorials/FieldDemoVideo.vue')['default']
    FieldInfo: typeof import('./src/components/tutorials/FieldInfo.vue')['default']
    FieldRenderer: typeof import('./src/components/tutorials/FieldRenderer.vue')['default']
    FieldText: typeof import('./src/components/tutorials/FieldText.vue')['default']
    FieldWarning: typeof import('./src/components/tutorials/FieldWarning.vue')['default']
    FloatingSearchBar: typeof import('./src/components/common/FloatingSearchBar.vue')['default']
    GrouperModal: typeof import('./src/components/modals/GrouperModal.vue')['default']
    HelpButton: typeof import('./src/components/navigation/helpButton.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    MyClassInsights: typeof import('./src/components/teacher/MyClassInsights.vue')['default']
    RankBadge: typeof import('./src/components/common/RankBadge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchoolAdminNav: typeof import('./src/components/admin/SchoolAdminNav.vue')['default']
    SchoolClassBarCharts: typeof import('./src/components/charts/SchoolClassBarCharts.vue')['default']
    SchoolInsights: typeof import('./src/components/teacher/SchoolInsights.vue')['default']
    Shop: typeof import('./src/components/Shop.vue')['default']
    StepsAndVideo: typeof import('./src/components/tutorials/StepsAndVideo.vue')['default']
    StudentConstraintsModal: typeof import('./src/components/modals/StudentConstraintsModal.vue')['default']
    TeacherInsights: typeof import('./src/components/teacher/TeacherInsights.vue')['default']
    TeacherNav: typeof import('./src/components/navigation/TeacherNav.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
    TopNav: typeof import('./src/components/navigation/topNav.vue')['default']
    TopStudentChips: typeof import('./src/components/common/TopStudentChips.vue')['default']
  }
}
