/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AwardPointsModal: typeof import('./src/components/modals/awardPointsModal.vue')['default']
    Classes: typeof import('./src/components/Classes.vue')['default']
    ClassForm: typeof import('./src/components/modals/ClassForm.vue')['default']
    ClassList: typeof import('./src/components/classList.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shop: typeof import('./src/components/Shop.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
  }
}
